# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48ee03f5bd66e71be50cd3ef38af753dd1c6c21bad4ad588bcce7035b7918c8e00665bcc1d3259fea5ff1382bf40a2ff72eff958bc77591fe00f833dc9161378

test:
  secret_key_base: 7f84b8be4ce2bebc9422ced647215bc85ec1429206ab132a5b0b11d574fe8cbc78c3afe1c35127ecbe5a7bf61289907b19fb3c1c1a9b6281a3e5a9ef959c579b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
